"""create worker 2 tables

Revision ID: 3bbdd23786df
Revises: 
Create Date: 2026-09-09 16:05:54.251191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bbdd23786df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('listing_pages', sa.Integer(), nullable=False),
    sa.Column('candidate_urls', sa.Integer(), nullable=False),
    sa.Column('jobs_extracted', sa.Integer(), nullable=False),
    sa.Column('jobs_saved', sa.Integer(), nullable=False),
    sa.Column('jobs_rejected', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_source_key'), 'ingestion_runs', ['source_key'], unique=False)
    op.create_table('job_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('jobs_seen_total', sa.Integer(), nullable=False),
    sa.Column('jobs_saved_total', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_sources_active'), 'job_sources', ['active'], unique=False)
    op.create_index(op.f('ix_job_sources_domain'), 'job_sources', ['domain'], unique=False)
    op.create_index(op.f('ix_job_sources_key'), 'job_sources', ['key'], unique=True)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('apply_url', sa.Text(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('company_name', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location_text', sa.Text(), nullable=True),
    sa.Column('locations', sa.JSON(), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=False),
    sa.Column('remote_scope', sa.String(length=50), nullable=False),
    sa.Column('eligible_countries', sa.JSON(), nullable=True),
    sa.Column('job_category', sa.String(length=100), nullable=True),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('seniority', sa.String(length=100), nullable=True),
    sa.Column('salary_text', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('eligibility_confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('extraction_method', sa.String(length=100), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_jobs_dedupe_key')
    )
    op.create_index(op.f('ix_jobs_canonical_url'), 'jobs', ['canonical_url'], unique=False)
    op.create_index(op.f('ix_jobs_dedupe_key'), 'jobs', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_jobs_external_id'), 'jobs', ['external_id'], unique=False)
    op.create_index(op.f('ix_jobs_job_category'), 'jobs', ['job_category'], unique=False)
    op.create_index(op.f('ix_jobs_posted_at'), 'jobs', ['posted_at'], unique=False)
    op.create_index(op.f('ix_jobs_quality_score'), 'jobs', ['quality_score'], unique=False)
    op.create_index(op.f('ix_jobs_remote'), 'jobs', ['remote'], unique=False)
    op.create_index(op.f('ix_jobs_remote_scope'), 'jobs', ['remote_scope'], unique=False)
    op.create_index(op.f('ix_jobs_source_key'), 'jobs', ['source_key'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_source_key'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_remote_scope'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_remote'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_quality_score'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_posted_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_category'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_external_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_dedupe_key'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_canonical_url'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_job_sources_key'), table_name='job_sources')
    op.drop_index(op.f('ix_job_sources_domain'), table_name='job_sources')
    op.drop_index(op.f('ix_job_sources_active'), table_name='job_sources')
    op.drop_table('job_sources')
    op.drop_index(op.f('ix_ingestion_runs_source_key'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
