"""add new block

Revision ID: b2d9f992fd4c
Revises: c64e05745baa
Create Date: 2026-08-14 11:36:37.740492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2d9f992fd4c'
down_revision: Union[str, Sequence[str], None] = 'c64e05745baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('description', sa.String(length=2000), nullable=True))
    op.add_column('companies', sa.Column('yc_batch', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('employee_count', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('is_hiring', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_companies_external_id'), 'companies', ['external_id'], unique=False)
    op.create_index(op.f('ix_companies_is_active'), 'companies', ['is_active'], unique=False)
    op.create_index(op.f('ix_companies_is_hiring'), 'companies', ['is_hiring'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_is_hiring'), table_name='companies')
    op.drop_index(op.f('ix_companies_is_active'), table_name='companies')
    op.drop_index(op.f('ix_companies_external_id'), table_name='companies')
    op.drop_column('companies', 'is_hiring')
    op.drop_column('companies', 'is_active')
    op.drop_column('companies', 'employee_count')
    op.drop_column('companies', 'yc_batch')
    op.drop_column('companies', 'description')
    op.drop_column('companies', 'location')
    # ### end Alembic commands ###
