"""add career persistence tables

Revision ID: bfa84c7addb6
Revises: 4feb17a94b47
Create Date: 2026-08-09 19:00:42.154587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa84c7addb6'
down_revision: Union[str, Sequence[str], None] = '4feb17a94b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id', 'company_id', name='uq_target_company_user_company')
    )
    op.create_index(op.f('ix_target_companies_clerk_user_id'), 'target_companies', ['clerk_user_id'], unique=False)
    op.create_index(op.f('ix_target_companies_company_id'), 'target_companies', ['company_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id', 'job_id', name='uq_recommendation_user_job')
    )
    op.create_index(op.f('ix_recommendations_clerk_user_id'), 'recommendations', ['clerk_user_id'], unique=False)
    op.create_index(op.f('ix_recommendations_job_id'), 'recommendations', ['job_id'], unique=False)
    op.create_table('seen_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id', 'job_id', name='uq_seen_job_user_job')
    )
    op.create_index(op.f('ix_seen_jobs_clerk_user_id'), 'seen_jobs', ['clerk_user_id'], unique=False)
    op.create_index(op.f('ix_seen_jobs_job_id'), 'seen_jobs', ['job_id'], unique=False)
    op.add_column('jobs', sa.Column('fingerprint', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_jobs_fingerprint'), 'jobs', ['fingerprint'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_fingerprint'), table_name='jobs')
    op.drop_column('jobs', 'fingerprint')
    op.drop_index(op.f('ix_seen_jobs_job_id'), table_name='seen_jobs')
    op.drop_index(op.f('ix_seen_jobs_clerk_user_id'), table_name='seen_jobs')
    op.drop_table('seen_jobs')
    op.drop_index(op.f('ix_recommendations_job_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_clerk_user_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_target_companies_company_id'), table_name='target_companies')
    op.drop_index(op.f('ix_target_companies_clerk_user_id'), table_name='target_companies')
    op.drop_table('target_companies')
    # ### end Alembic commands ###
