"""add telegram linking fields

Revision ID: c64e05745baa
Revises: de7e69edc8a6
Create Date: 2026-08-11 21:42:05.666171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c64e05745baa'
down_revision: Union[str, Sequence[str], None] = 'de7e69edc8a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_link_tokens_telegram_chat_id'), table_name='telegram_link_tokens')
    op.drop_index(op.f('ix_telegram_link_tokens_token'), table_name='telegram_link_tokens')
    op.drop_table('telegram_link_tokens')
    op.add_column('telegram_accounts', sa.Column('link_code', sa.String(length=20), nullable=True))
    op.add_column('telegram_accounts', sa.Column('link_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('telegram_accounts', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('telegram_accounts', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('telegram_accounts', 'telegram_chat_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=True)
    op.drop_constraint(op.f('uq_telegram_account_chat'), 'telegram_accounts', type_='unique')
    op.drop_constraint(op.f('uq_telegram_account_clerk_user'), 'telegram_accounts', type_='unique')
    op.drop_index(op.f('ix_telegram_accounts_clerk_user_id'), table_name='telegram_accounts')
    op.create_index(op.f('ix_telegram_accounts_clerk_user_id'), 'telegram_accounts', ['clerk_user_id'], unique=True)
    op.drop_index(op.f('ix_telegram_accounts_telegram_chat_id'), table_name='telegram_accounts')
    op.create_index(op.f('ix_telegram_accounts_telegram_chat_id'), 'telegram_accounts', ['telegram_chat_id'], unique=True)
    op.create_index(op.f('ix_telegram_accounts_link_code'), 'telegram_accounts', ['link_code'], unique=True)
    op.drop_column('telegram_accounts', 'telegram_username')
    op.drop_column('telegram_accounts', 'linked_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_accounts', sa.Column('linked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('telegram_accounts', sa.Column('telegram_username', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_telegram_accounts_link_code'), table_name='telegram_accounts')
    op.drop_index(op.f('ix_telegram_accounts_telegram_chat_id'), table_name='telegram_accounts')
    op.create_index(op.f('ix_telegram_accounts_telegram_chat_id'), 'telegram_accounts', ['telegram_chat_id'], unique=False)
    op.drop_index(op.f('ix_telegram_accounts_clerk_user_id'), table_name='telegram_accounts')
    op.create_index(op.f('ix_telegram_accounts_clerk_user_id'), 'telegram_accounts', ['clerk_user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_telegram_account_clerk_user'), 'telegram_accounts', ['clerk_user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_telegram_account_chat'), 'telegram_accounts', ['telegram_chat_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('telegram_accounts', 'telegram_chat_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('telegram_accounts', 'updated_at')
    op.drop_column('telegram_accounts', 'created_at')
    op.drop_column('telegram_accounts', 'link_code_expires_at')
    op.drop_column('telegram_accounts', 'link_code')
    op.create_table('telegram_link_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('telegram_chat_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('telegram_link_tokens_pkey'))
    )
    op.create_index(op.f('ix_telegram_link_tokens_token'), 'telegram_link_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_telegram_link_tokens_telegram_chat_id'), 'telegram_link_tokens', ['telegram_chat_id'], unique=False)
    # ### end Alembic commands ###
