"""add telegram account linking

Revision ID: de7e69edc8a6
Revises: bfa84c7addb6
Create Date: 2026-08-11 13:06:10.288218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de7e69edc8a6'
down_revision: Union[str, Sequence[str], None] = 'bfa84c7addb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=255), nullable=False),
    sa.Column('telegram_username', sa.String(length=255), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id', name='uq_telegram_account_clerk_user'),
    sa.UniqueConstraint('telegram_chat_id', name='uq_telegram_account_chat')
    )
    op.create_index(op.f('ix_telegram_accounts_clerk_user_id'), 'telegram_accounts', ['clerk_user_id'], unique=False)
    op.create_index(op.f('ix_telegram_accounts_telegram_chat_id'), 'telegram_accounts', ['telegram_chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_accounts_telegram_chat_id'), table_name='telegram_accounts')
    op.drop_index(op.f('ix_telegram_accounts_clerk_user_id'), table_name='telegram_accounts')
    op.drop_table('telegram_accounts')
    # ### end Alembic commands ###
