[project]
name = "l-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.22.1",
    "alembic>=1.19.1",
    "beautifulsoup4>=4.15.0",
    "clerk-backend-api>=6.0.1",
    "fastapi[standard]>=0.141.1",
    "google-genai>=2.18.1",
    "groq>=1.6.0",
    "httpx>=0.28.1",
    "psycopg2>=2.9.12",
    "psycopg[binary]>=3.3.4",
    "pydantic-settings>=2.14.2",
    "pypdf>=6.14.2",
    "python-docx>=1.2.0",
    "python-multipart>=0.0.32",
    "rich>=15.0.0",
    "sqlalchemy>=2.0.51",
    "tavily-python>=0.7.27",
    "uvicorn[standard]>=0.52.1",
]

[tool.uv]
dev-dependencies = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.16.1",
    "httpx2>=2.9.1",
]
[tool.ruff.lint.flake8-bugbear]
# 🚀 Allow FastAPI dependency injection
extend-immutable-calls = ["fastapi.Depends"]
